# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15-Vl1BaoOT0T1Ypz3LCmFZVegiiEWb7n
"""

from google.colab import files
uploaded=files.upload()

from google.colab import files
uploaded=files.upload()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# -------------------------
# Load Cleaned Dataset
# -------------------------
df = pd.read_csv("visa_dataset_cleaned.csv")

print("Dataset Shape:", df.shape)
print(df.head())

# -------------------------
# BASIC EDA
# -------------------------

# Processing time distribution
plt.figure()
sns.histplot(df['processing_time'], kde=True)
plt.title("Processing Time Distribution")
plt.xlabel("Processing Time (days)")
plt.ylabel("Count")
plt.show()

# Processing time by visa type
plt.figure()
sns.boxplot(x='visa_type', y='processing_time', data=df)
plt.title("Processing Time by Visa Type")
plt.show()

# Processing time by country
plt.figure()
sns.boxplot(x='applicant_country', y='processing_time', data=df)
plt.title("Processing Time by Country")
plt.show()

# -------------------------
# CORRELATION ANALYSIS
# -------------------------

plt.figure(figsize=(10,6))
sns.heatmap(df.corr(), annot=True, cmap="coolwarm")
plt.title("Feature Correlation Heatmap")
plt.show()

# -------------------------
# FEATURE ENGINEERING
# -------------------------

# Reload original dataset with dates
raw = pd.read_csv("visastatus_dataset.csv")

raw['application_date'] = pd.to_datetime(raw['application_date'])
raw['decision_date'] = pd.to_datetime(raw['decision_date'])

# Time features
raw['application_month'] = raw['application_date'].dt.month
raw['application_year'] = raw['application_date'].dt.year
raw['quarter'] = raw['application_date'].dt.quarter

# Season mapping
def get_season(month):
    if month in [12,1,2]:
        return "Winter"
    elif month in [3,4,5]:
        return "Summer"
    elif month in [6,7,8]:
        return "Monsoon"
    else:
        return "Autumn"

raw['season'] = raw['application_month'].apply(get_season)

# Processing time again
raw['processing_time'] = (raw['decision_date'] - raw['application_date']).dt.days

# Country average processing time
country_avg = raw.groupby('applicant_country')['processing_time'].mean()
raw['country_avg_time'] = raw['applicant_country'].map(country_avg)

# Monthly application count
monthly_count = raw.groupby('application_month').size()
raw['monthly_application_count'] = raw['application_month'].map(monthly_count)

# Country-month workload
country_month = raw.groupby(['applicant_country','application_month']).size()
raw['country_month_count'] = raw.set_index(
    ['applicant_country','application_month']
).index.map(country_month)

# -------------------------
# SEASONAL ANALYSIS PLOTS
# -------------------------

plt.figure()
sns.boxplot(x='season', y='processing_time', data=raw)
plt.title("Processing Time by Season")
plt.show()

plt.figure()
sns.lineplot(x='application_month', y='processing_time', data=raw)
plt.title("Processing Time by Month")
plt.show()

# -------------------------
# COUNTRY AVERAGE PLOT
# -------------------------

country_plot = raw.groupby('applicant_country')['processing_time'].mean()

plt.figure()
country_plot.plot(kind='bar')
plt.title("Average Processing Time by Country")
plt.ylabel("Days")
plt.show()

# -------------------------
# SAVE FEATURE DATASET
# -------------------------
raw.to_csv("visa_dataset_features.csv", index=False)


print("Feature dataset saved as visa_dataset_features.csv")

from google.colab import files
files.download('visa_dataset_features.csv')