# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15-Vl1BaoOT0T1Ypz3LCmFZVegiiEWb7n
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error


# LOAD DATASET

df = pd.read_csv("visa_dataset_features.csv")

print("Dataset Shape:", df.shape)
print(df.head())



# DATA CLEANING


# Handle missing target values
df['processing_time'] = df['processing_time'].fillna(df['processing_time'].mean())



# DEFINE FEATURES AND TARGET

X = df.drop("processing_time", axis=1)
y = df["processing_time"]



# CONVERT CATEGORICAL DATA

X = pd.get_dummies(X)



# HANDLE MISSING VALUES

X = X.fillna(X.mean())



# TRAIN TEST SPLIT

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)



# LINEAR REGRESSION MODEL

lr = LinearRegression()
lr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)

lr_mae = mean_absolute_error(y_test, lr_pred)
lr_rmse = np.sqrt(mean_squared_error(y_test, lr_pred))

print("\nLinear Regression Results")
print("MAE:", lr_mae)
print("RMSE:", lr_rmse)



# RANDOM FOREST MODEL

rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)

rf_mae = mean_absolute_error(y_test, rf_pred)
rf_rmse = np.sqrt(mean_squared_error(y_test, rf_pred))

print("\nRandom Forest Results")
print("MAE:", rf_mae)
print("RMSE:", rf_rmse)



# BEST MODEL

if rf_rmse < lr_rmse:
    print("\nBest Model: Random Forest")
else:
    print("\nBest Model: Linear Regression")



# VISUALIZATION


plt.figure(figsize=(6,6))
plt.scatter(y_test, rf_pred)
plt.xlabel("Actual Processing Time")
plt.ylabel("Predicted Processing Time")
plt.title("Actual vs Predicted")
plt.show()